# Generated by Django 6.0.4 on 2026-06-04 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Activo'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('H', 'Huesped'), ('P', 'Propietario'), ('A', 'Administrador')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='calle',
            field=models.CharField(choices=[('HT', 'Hotel'), ('HS', 'Hostel'), ('CA', 'Casa'), ('DP', 'Departamento'), ('CB', 'Cabana')], default='HT', max_length=50),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='descripción',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SolicitudPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
