# Generated by Django 6.0.4 on 2026-06-04 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0002_alojamiento_estado_alojamiento_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
