# Generated by Django 6.0.6 on 2026-06-04 13:10

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0003_alter_alojamiento_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpropietario',
            name='fecha_solicitud',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
