# Generated by Django 6.0.6 on 2026-06-04 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0004_alter_solicitudpropietario_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudpropietario',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
