# Generated by Django 6.0.4 on 2026-07-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0006_alter_alojamiento_tipo_alter_alojamiento_calle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_finalización',
            new_name='fecha_finalizacion',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_inico',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='Confirmada', max_length=20),
        ),
    ]
