# Generated by Django 6.0.7 on 2026-09-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0007_rename_fecha_finalización_reserva_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alojamiento',
            options={'verbose_name': 'Alojamiento', 'verbose_name_plural': 'Alojamientos'},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='reseña',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='solicitudpropietario',
            options={'verbose_name': 'Solicitud de Propietario', 'verbose_name_plural': 'Solicitudes de Propietarios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Indica si la habitacion esta disponible para ser reservada. El propietario puede cambiarlo manualmente.'),
        ),
    ]
