# Generated by Django 6.0.7 on 2026-09-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0008_add_disponible_to_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='fecha_desocupacion_automatica',
            field=models.DateField(blank=True, help_text='Fecha en la que finaliza la reserva activa para desocupar la habitacion automaticamente.', null=True),
        ),
    ]
