# Generated by Django 6.0.4 on 2026-09-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0009_add_fecha_desocupacion_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(help_text='Identificador interno', max_length=30, unique=True)),
                ('icono_svg', models.TextField(help_text='SVG inline del icono')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='hoteles/', verbose_name='Imagen')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='hotelghino.alojamiento')),
            ],
            options={
                'verbose_name': 'Imagen de alojamiento',
                'verbose_name_plural': 'Imágenes de alojamiento',
                'ordering': ['-es_principal', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='hotelghino.servicioalojamiento', verbose_name='Servicios del alojamiento'),
        ),
    ]
