# Generated by Django 6.0.7 on 2026-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0011_alojamiento_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad o localidad'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='direccion_completa',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección completa'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='pais',
            field=models.CharField(blank=True, default='Argentina', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia o región'),
        ),
    ]
