# Generated by Django 6.0.7 on 2026-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0012_alojamiento_ciudad_alojamiento_direccion_completa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='numero_calle',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
