# Generated by Django 6.0.4 on 2026-10-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0013_alter_alojamiento_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='ubicacion',
            field=models.CharField(blank=True, default='Mar del Plata', max_length=100, verbose_name='Ubicación / Ciudad'),
        ),
    ]
