# Generated by Django 6.0.7 on 2026-10-07 01:46

from django.db import migrations, models


def marcar_usuarios_existentes_como_verificados(apps, schema_editor):
    Usuario = apps.get_model('hotelghino', 'Usuario')
    Usuario.objects.all().update(email_verificado=True)


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotelghino', '0014_alter_alojamiento_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha verificado su dirección de correo electrónico.', verbose_name='Email verificado'),
        ),
        migrations.RunPython(
            marcar_usuarios_existentes_como_verificados,
            reverse_code=revertir,
        ),
    ]
